### ISSUE TITLE
Build static containers/routes

### ISSUE THREAD

**Issue by Karyum** [FACN1/PAS-MVP#23]
- [x] Select guesthouse page ref #22 
- [x] Travel method page ref #2 
- [x] Car/Taxi/Bus page ref #3 #7 #9 
- [x] Walking directions ref #5 #8 
- [x] Success page ref #6 
- [x] Add the routes for them 
- [x] Setup empty child component files 
- [x] Remove Counter and test for the Counter
